//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anketHazırlama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anket()
        {
            this.Sonuc = new HashSet<Sonuc>();
        }
    
        public int anketId { get; set; }
        public string anketBaslik { get; set; }
        public string anketSoruları { get; set; }
        public System.DateTime anketTarih { get; set; }
        public int anketKategoriId { get; set; }
        public int anketUyeId { get; set; }
        public int anketOkunma { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Uye Uye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sonuc> Sonuc { get; set; }
    }
}
