//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace anketHazırlama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sonuc
    {
        public int sonucId { get; set; }
        public string sonucIcerik { get; set; }
        public int sonucUyeId { get; set; }
        public int sonucAnketId { get; set; }
        public System.DateTime sonucTarih { get; set; }
    
        public virtual Anket Anket { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
